### ISSUE TITLE
Support `uuid()`

### ISSUE THREAD

**Issue by Shinigami92** [g45t345rt/minifaker#1]
Could you add support for `uuid` and maybe just use a optional peerDependency for `nanoid`?
That way we could just use one faker API instead of two different tools for generating random data.

**Comment by JeffBeltran** [comment]
After looking things over, maybe just open a PR? since the project already has a peer dependency [import seedrandom from 'seedrandom'](https://github.com/g45t345rt/minifaker/blob/c4b06b83bfa803b08a4a5cc19117bae3e579ffea/src/index.ts#L1). I understand size === bad for most people but for this project i'm not sure where that would be a concern

**Comment by Shinigami92** [comment]
For now I will have an eye on https://github.com/withshepherd/faker.js and how it will spread.
If it has no future, I'm happy to contribute this requested change.

**Comment by eswat2** [comment]
here's another that pop'd up today -- https://github.com/MilosPaunovic/community-faker

**Comment by eswat2** [comment]
for what it's worth, i uses this little code snippet to mock UUIDs:

```
function b(a) {
  return a
    ? (a ^ ((Math.random() * 16) >> (a / 4))).toString(16)
    : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, b)
}
```

You can see an example response here -- https://mock-342.herokuapp.com/api/uuid

**Comment by g45t345rt** [comment]
I've made changes to support `uuid` and other packages
https://github.com/g45t345rt/minifaker#direct-access-to-more-performantpopular-packages

@Shinigami92 Is this what you were looking for?
